# Generated by Django 3.0 on 2021-07-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('mobile', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=75)),
                ('website', models.CharField(max_length=75)),
                ('twitter', models.CharField(max_length=75)),
                ('instgram', models.CharField(max_length=75)),
                ('facebook', models.CharField(max_length=75)),
            ],
        ),
    ]
